# Generated by Django 4.1.7 on 2023-04-16 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Họ_và_Tên', models.CharField(default='', help_text='Name', max_length=200)),
                ('Tuổi', models.IntegerField(help_text='Age')),
                ('Ngày_sinh', models.DateField(blank=True, help_text='Birthday', null=True)),
                ('Số_điện_thoại', models.CharField(default='', help_text='Phone number', max_length=20)),
                ('Nơi_ở', models.CharField(help_text='Location', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Vaccine across whole library', primary_key=True, serialize=False)),
                ('Tên_Vaccine', models.CharField(help_text='Name of vaccine', max_length=200)),
                ('Ngày_tiêm', models.DateField(blank=True, help_text='Date', null=True)),
                ('Nơi_tiêm', models.CharField(help_text='Name of provider', max_length=200)),
            ],
            options={
                'ordering': ['Ngày_tiêm'],
            },
        ),
    ]
