# Generated by Django 4.1.7 on 2023-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Tuổi',
            field=models.IntegerField(help_text='Age'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Ngày_sinh',
            field=models.DateField(blank=True, null=True, help_text='Birthday'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Số_điện_thoại',
            field=models.CharField(max_length=20, help_text='Phone number', default=''),
        ),
    ]