# Generated by Django 4.1.7 on 2023-04-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20230416_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Ngày_tiêm',
        ),
    ]
