# Generated by Django 4.1.7 on 2023-04-17 02:09

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_personalinfo_ngày_tiêm'),
    ]

    operations = [
    migrations.AddField(
        model_name='vaccineinfo',
        name='Ngày_tiêm',
        field=models.DateField(blank=True, null=True, help_text='Date'),
    ),
]
