# Generated by Django 4.1.7 on 2023-05-18 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Tuổi',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Tuoi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Họ_và_Tên',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Ngày_sinh',
            field=models.DateField(blank=True, help_text='(vd: 2002-08-31)', null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Nơi_ở',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Số_điện_thoại',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username', max_length=254),
        ),
        migrations.AlterField(
            model_name='vaccineinfo',
            name='Ngày_tiêm',
            field=models.DateField(blank=True, help_text='(vd: 2002-08-31)', null=True),
        ),
        migrations.AlterField(
            model_name='vaccineinfo',
            name='Nơi_tiêm',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccineinfo',
            name='Tên_Vaccine',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccineinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
