# Generated by Django 4.1.7 on 2023-05-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_remove_personalinfo_tuổi_personalinfo_tuoi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Nơi_ở',
        ),
    ]
