# Generated by Django 4.1.7 on 2023-05-21 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0009_personalinfo_user_vaccineinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
