# Generated by Django 4.1.7 on 2023-05-22 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_alter_relative_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeVaccineInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Tên_Vaccine', models.CharField(max_length=200)),
                ('Ngày_tiêm', models.DateField(blank=True, help_text='(vd: 2002-08-31)', null=True)),
                ('Nơi_tiêm', models.CharField(max_length=200)),
                ('Sức_khỏe_trước_khi_tiêm', models.TextField(blank=True)),
                ('Sức_khỏe_sau_khi_tiêm', models.TextField(blank=True)),
                ('Liều_lượng', models.CharField(blank=True, max_length=200)),
                ('Ghi_chú', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.user')),
            ],
            options={
                'ordering': ['Tên_Vaccine'],
            },
        ),
    ]
