# Generated by Django 4.1.7 on 2023-05-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_alter_relativevaccineinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Họ_và_Tên', models.CharField(default='', max_length=200)),
                ('Tên_Vaccine', models.CharField(max_length=200)),
                ('Ngày_sinh', models.DateField(blank=True, help_text='(vd: 2002-08-31)', null=True)),
                ('Số_điện_thoại', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
