# Generated by Django 4.1.7 on 2023-05-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineinfo',
            name='personal_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.personalinfo'),
        ),
    ]
