# Generated by Django 4.1.7 on 2023-05-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_vaccineinfo_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='relativevaccineinfo',
            name='relative_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.relative'),
        ),
    ]
