# Generated by Django 4.1.7 on 2023-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0019_relativevaccineinfo_relative_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='Relative_name',
            field=models.CharField(help_text='Họ và tên', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='Role',
            field=models.CharField(help_text='Quan hệ', max_length=200, null=True),
        ),
    ]
